# Generated by Django 4.0.3 on 2022-03-27 22:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schedules', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='route',
            name='route_type',
            field=models.ManyToManyField(related_name='routes', to='schedules.routetype'),
        ),
        migrations.AddField(
            model_name='order',
            name='node_geom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedule_orders', to='schedules.node'),
        ),
        migrations.AddField(
            model_name='order',
            name='route_geom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedule_orders', to='schedules.route'),
        ),
        migrations.AddField(
            model_name='order',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_orders', to='schedules.schedule'),
        ),
    ]
