# Generated by Django 4.0.3 on 2022-04-03 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0002_initial'),
        ('routes', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='schedule_order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='place', to='schedules.order'),
        ),
        migrations.AlterField(
            model_name='transitdetail',
            name='transit_step',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transit_detail', to='routes.step'),
        ),
    ]
