# Generated by Django 4.0.4 on 2022-04-22 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transitdetail',
            name='transit_short_name',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
