# Generated by Django 4.0.3 on 2022-04-01 14:12

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='poly_line',
            field=django.contrib.gis.db.models.fields.GeometryField(srid=900913),
        ),
        migrations.AlterField(
            model_name='step',
            name='poly_line',
            field=django.contrib.gis.db.models.fields.GeometryField(srid=900913),
        ),
        migrations.AlterField(
            model_name='walkingdetail',
            name='poly_line',
            field=django.contrib.gis.db.models.fields.GeometryField(srid=900913),
        ),
    ]
