# Generated by Django 4.0.3 on 2022-04-05 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WalkingDetail',
        ),
    ]
