# Generated by Django 4.0.3 on 2022-04-03 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0002_initial'),
        ('routes', '0003_alter_place_schedule_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='schedule_order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='schedules.order'),
        ),
    ]
