# Generated by Django 4.0.3 on 2022-04-03 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0005_alter_schedule_user'),
        ('routes', '0004_alter_route_schedule_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='schedule_order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='route', to='schedules.order'),
        ),
    ]
