# Generated by Django 4.0.3 on 2022-04-04 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0005_alter_schedule_user'),
        ('routes', '0005_alter_route_schedule_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='schedule_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='place', to='schedules.order'),
        ),
        migrations.AlterField(
            model_name='route',
            name='schedule_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route', to='schedules.order'),
        ),
    ]
